[package]
name = "ki-egui"
version = "0.0.1"
edition = "2021"

[dependencies]
eframe = "0.30.0"
egui = "0.30.0"
egui_extras = "0.30.0"
env_logger = "0.11.6"
ki-core = { path = "../ki-core" }
log = { workspace = true }
