[package]
name = "ki-core"
version = "0.0.1"
edition = "2021"

[dependencies]
rdkafka = { version = "0.36.2", features = ["cmake-build"] }
log = { workspace = true }
tokio = { version = "1.42.0", features = ["rt-multi-thread"] }
