[package]
name = "ki-core"
version = "0.0.1"
edition = "2021"

[dependencies]
rdkafka = { version = "0.36.2", features = ["cmake-build"] }
serde = { workspace = true }
serde_json = { workspace = true }
log = { workspace = true }
